# Generated by Django 4.2.1 on 2023-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_remove_experience_gallary_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
