# Generated by Django 4.2.1 on 2023-10-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_experience_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='categories',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
